### ISSUE TITLE
Cannot read properties of null (reading 'querySelector') in Mx 10.3

### ISSUE THREAD

**Issue by dimenus** [hunter-koppen/DataGrid2ResetFilters#2]
I am unable to use this module as of Mx 10.3. 

```
// Open the dropdown list
filter[react].onClick();

const dropdown = document.querySelector('#' + ctrls);
const multiSelect = dropdown.querySelector('input') !== null;
```

The querySelector call doesn't return anything. I'm not a javascript expert, but it looks like the `OnClick` is executed asynchronously and therefore won't populate the DOM with the nodes you're depending on later in the script.

https://github.com/mendix/web-widgets/blob/main/packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/FilterComponent.tsx#L162

**Comment by hunter-koppen** [comment]
Hi @dimenus you are right, Mendix seems to handle the onclick differently since 10.3. I have updated the module with a new version that will wait for the onClick to finish opening the dropdown.

Thanks for reporting it, I'll close the issue for now, If you still experience problems then please re-open it :).
